@startuml EPS_BDD

' Stereotypes for SysML blocks
skinparam class {
    BackgroundColor<<block>> LightYellow
    BorderColor<<block>> Black
}

class "Electric Power Steering (EPS)" as EPS <<block>>
class "Torque Sensor" as TS <<block>>
class "Steering Angle Sensor" as SAS <<block>>
class "Vehicle Speed Sensor" as VSS <<block>>
class "Electric Motor" as EM <<block>>
class "Motor Driver / ECU" as ECU <<block>>
class "Reduction Gear / Ball Screw" as RG <<block>>
class "Battery / Power Supply" as BAT <<block>>
class "ADAS Controller" as ADAS <<block>>
class "Vehicle CAN Bus" as CAN <<block>>
class "Steering Wheel" as SW <<block>>
class "Steering Rack" as SR <<block>>

EPS -- TS : reads torque
EPS -- SAS : reads angle
EPS -- VSS : reads speed
EPS -- EM : drives
EPS -- ECU : controls
EPS -- RG : actuates
EPS -- BAT : powers
EPS -- ADAS : ADAS override
EPS -- CAN : communicates
EPS -- SW : interfaces
EPS -- SR : actuates

TS -- SW : measures
SAS -- SW : measures
EM -- RG : rotates
RG -- SR : moves
ECU -- EM : controls
ECU -- ADAS : receives ADAS cmd
ECU -- CAN : communicates
ECU -- BAT : powers

@enduml 